Format shell scripts

diff --git a/bin/rpbcopy-server b/bin/rpbcopy-server
--- a/bin/rpbcopy-server
+++ b/bin/rpbcopy-server
@@ -2,10 +2,10 @@
 
 set -e
 
-usage () {
-	SCRIPT=$(basename "$0");
-	if ( ! which "$SCRIPT" > /dev/null ); then
-		SCRIPT="$0";
+usage() {
+	SCRIPT=$(basename "$0")
+	if (! which "$SCRIPT" >/dev/null); then
+		SCRIPT="$0"
 	fi
 
 	cat >&2 <<EOF
@@ -18,40 +18,40 @@ PORT should be in the range 1025 - 65535.
 Using 58827 was randomly selected from the range using random.org.
 EOF
 
-	exit "$1";
+	exit "$1"
 }
 
 if [ $# != 1 ]; then
-	echo "Missing PORT" >&2;
-	usage 2;
+	echo "Missing PORT" >&2
+	usage 2
 fi
 
-PORT="$1";
+PORT="$1"
 if ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
-	echo "Bad Port Value: '$PORT'. Must be an int." >&2;
-	usage 3;
+	echo "Bad Port Value: '$PORT'. Must be an int." >&2
+	usage 3
 fi
 
 if [ "$PORT" -lt 1025 ] || [ "$PORT" -gt 65535 ]; then
-	echo "Bad Port Value: '$PORT'. Not in range." >&2;
-	usage 4;
+	echo "Bad Port Value: '$PORT'. Not in range." >&2
+	usage 4
 fi
 
 # Do this after validating all of the parameters.
 
 # Requires brew install liblockfile.
-LOCK="$(basename "$0" '.sh').lock";
+LOCK="$(basename "$0" '.sh').lock"
 dotlockfile -p -l -r 0 "$TMPDIR/$LOCK" || {
-	echo "$0 already running, cannot obtain lock." >&2;
-	exit 5;
+	echo "$0 already running, cannot obtain lock." >&2
+	exit 5
 }
 #echo "Created Lockfile: $TMPDIR/$LOCK";
 
-finish () {
-	dotlockfile -p -u "$TMPDIR/$LOCK";
+finish() {
+	dotlockfile -p -u "$TMPDIR/$LOCK"
 }
-trap finish EXIT;
+trap finish EXIT
 
-while (true); do 
-	nc -l "$PORT" | pbcopy; 
+while (true); do
+	nc -l "$PORT" | pbcopy
 done
diff --git a/bin/snano b/bin/snano
--- a/bin/snano
+++ b/bin/snano
@@ -1,28 +1,28 @@
 #!/bin/bash
 
-set -e;
+set -e
 
 real_path() {
-	if ( which realpath > /dev/null ); then
-		REAL_PATH=$(realpath "$1");
+	if (which realpath >/dev/null); then
+		REAL_PATH=$(realpath "$1")
 	else
-		TARGET_FILE=$(basename "$1");
-		TARGET_DIR=$(dirname "$1");
-		cd "$TARGET_DIR";
-		REAL_DIR=$(pwd -P);
-		REAL_PATH="$REAL_DIR/$TARGET_FILE";		
-		cd "$OLDPWD";
+		TARGET_FILE=$(basename "$1")
+		TARGET_DIR=$(dirname "$1")
+		cd "$TARGET_DIR"
+		REAL_DIR=$(pwd -P)
+		REAL_PATH="$REAL_DIR/$TARGET_FILE"
+		cd "$OLDPWD"
 	fi
 
-	echo "$REAL_PATH";
+	echo "$REAL_PATH"
 }
 
-KEEP_ORIG=true;
+KEEP_ORIG=true
 
 usage() {
-	SCRIPT=$(basename "$0");
-	if ( ! which "$SCRIPT" > /dev/null ); then
-		SCRIPT="$0";
+	SCRIPT=$(basename "$0")
+	if (! which "$SCRIPT" >/dev/null); then
+		SCRIPT="$0"
 	fi
 
 	cat >&2 <<EOF
@@ -37,66 +37,66 @@ OPTIONS:
 	-h	Show this help text
 	-o	Overwrite Original backup of FILENAME
 EOF
-	exit "$1";
+	exit "$1"
 }
 
 while getopts ":ho" OPT; do
 	case $OPT in
-		h)
-			usage 0;
+	h)
+		usage 0
 		;;
-		o)
-			echo "Replacing Original Before File" >&2;
-			KEEP_ORIG=false;
-			shift;
+	o)
+		echo "Replacing Original Before File" >&2
+		KEEP_ORIG=false
+		shift
 		;;
-		\?)
-			echo "Invalid option: -$OPTARG" >&2;
-			usage 3;
+	\?)
+		echo "Invalid option: -$OPTARG" >&2
+		usage 3
 		;;
 	esac
 done
 
 # Check for required parameters
 if [ $# != 1 ]; then
-	echo "Missing Filename" >&2;
-	usage 2;
+	echo "Missing Filename" >&2
+	usage 2
 fi
 
 if [ ! -f "$1" ]; then
 	# If the file doesn't exist, create directory structure & empty file
-	DIR=$(dirname "$1");
-	sudo mkdir -p "$DIR";
-	sudo touch "$1";
+	DIR=$(dirname "$1")
+	sudo mkdir -p "$DIR"
+	sudo touch "$1"
 fi
 
-WRKFILE=$(real_path "$1");
-BACKUPDIR="$HOME/backups$WRKFILE";
+WRKFILE=$(real_path "$1")
+BACKUPDIR="$HOME/backups$WRKFILE"
 
-mkdir -p "$BACKUPDIR";
+mkdir -p "$BACKUPDIR"
 
-if ( $KEEP_ORIG ); then
+if ($KEEP_ORIG); then
 	if [ ! -f "$BACKUPDIR/before" ]; then
-		sudo cp -a "$WRKFILE" "$BACKUPDIR/before";
+		sudo cp -a "$WRKFILE" "$BACKUPDIR/before"
 	fi
 else
-	sudo rm -f "$BACKUPDIR/before";
-	sudo cp -a "$WRKFILE" "$BACKUPDIR/before";
+	sudo rm -f "$BACKUPDIR/before"
+	sudo cp -a "$WRKFILE" "$BACKUPDIR/before"
 fi
 
-sudo nano "$WRKFILE";
+sudo nano "$WRKFILE"
 
-sudo rm -f "$BACKUPDIR/after";
-sudo cp -a "$WRKFILE" "$BACKUPDIR/after";
+sudo rm -f "$BACKUPDIR/after"
+sudo cp -a "$WRKFILE" "$BACKUPDIR/after"
 
-GID=$(id -g);
-sudo chown "$UID:$GID" "$BACKUPDIR"/*;
+GID=$(id -g)
+sudo chown "$UID:$GID" "$BACKUPDIR"/*
 
 # Cleanup .nano_history ownership
 if [ -f "$HOME/.nano_history" -a ! -O "$HOME/.nano_history" ]; then
-	sudo chown "$UID:$GID" "$HOME/.nano_history";
+	sudo chown "$UID:$GID" "$HOME/.nano_history"
 fi
 
-/usr/bin/diff --unified "$BACKUPDIR/before" "$BACKUPDIR/after" > "$BACKUPDIR/diff";
+/usr/bin/diff --unified "$BACKUPDIR/before" "$BACKUPDIR/after" >"$BACKUPDIR/diff"
 
-echo "Backups Stored: '$BACKUPDIR'" >&2;
+echo "Backups Stored: '$BACKUPDIR'" >&2
